pub mod solve2;
pub mod solve3;
pub mod solve4;
pub mod solve5;
pub mod solve6;
pub mod solve6b;
pub mod solve6c;
pub mod solve6d;
#[cfg(feature = "hash")]
pub mod solve6e;
#[cfg(feature = "hash")]
pub mod solve6f;
#[cfg(feature = "hash")]
pub mod solve6g;
#[cfg(feature = "hash")]
pub mod solve6h;
#[cfg(feature = "hash")]
pub mod solve6i;
#[cfg(feature = "hash")]
pub mod solve6j;
#[cfg(feature = "hash")]
pub mod solve6k;
#[cfg(feature = "hash")]
pub mod solve6l;
#[cfg(feature = "hash")]
pub mod solve6m;
#[cfg(feature = "hash")]
pub mod solve6m2;
pub mod solve6n;
#[cfg(feature = "hash")]
pub mod solve6o;
#[cfg(feature = "hash")]
pub mod solve6p;
#[cfg(feature = "hash")]
pub mod solve6q;
#[cfg(feature = "hash")]
pub mod solve6r;
pub mod solve6s;
pub mod solve6t;
pub mod solve6u;
pub mod solve6v;
pub mod solve6w;
pub mod solve6x;
pub mod solve6y;
pub mod solve6z;

pub use solve6z as latest;
